"""Measure MITRE ATT&CK coverage of the rule set.

Produces two artifacts from the ATT&CK tags on the rules:

* ``navigator_layer.json`` — an ATT&CK Navigator layer that highlights every
  covered technique (importable at https://mitre-attack.github.io/attack-navigator/);
* ``coverage_summary.md`` — a human-readable summary with, per tactic, the
  number of techniques covered and the percentage of that tactic's techniques.

The per-tactic denominator uses a static snapshot of ATT&CK Enterprise technique
counts (:data:`ATTACK_TECHNIQUE_TOTALS`). The point of the percentage is to make
coverage *trackable over time*, not to be a precise live figure — the snapshot
version is recorded in the output so it can be refreshed deliberately.
"""

from __future__ import annotations

import json
import logging
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path

from sentinelcode.rules import LoadedRule, load_rules

logger = logging.getLogger(__name__)

# ATT&CK version the static technique totals below correspond to.
ATTACK_VERSION = "15"
NAVIGATOR_LAYER_VERSION = "4.5"
NAVIGATOR_APP_VERSION = "4.9.1"

# Approximate count of (base) techniques per ATT&CK Enterprise tactic for the
# snapshot above. Used as the denominator for per-tactic coverage percentages.
ATTACK_TECHNIQUE_TOTALS: dict[str, int] = {
    "reconnaissance": 10,
    "resource_development": 8,
    "initial_access": 10,
    "execution": 14,
    "persistence": 19,
    "privilege_escalation": 13,
    "defense_evasion": 43,
    "credential_access": 17,
    "discovery": 32,
    "lateral_movement": 9,
    "collection": 17,
    "command_and_control": 17,
    "exfiltration": 9,
    "impact": 14,
}

# Colour used to highlight covered techniques in the Navigator layer.
_COVERED_COLOR = "#2e7d32"


@dataclass
class TacticCoverage:
    """Coverage figures for a single ATT&CK tactic."""

    tactic: str
    covered_base_techniques: set[str] = field(default_factory=set)

    @property
    def total(self) -> int:
        return ATTACK_TECHNIQUE_TOTALS.get(self.tactic, 0)

    @property
    def covered(self) -> int:
        return len(self.covered_base_techniques)

    @property
    def percentage(self) -> float:
        if not self.total:
            return 0.0
        return round(100.0 * self.covered / self.total, 1)


@dataclass
class CoverageReport:
    """Aggregated ATT&CK coverage across the whole rule set."""

    tactics: dict[str, TacticCoverage] = field(default_factory=dict)
    #: technique id -> sorted list of rule titles that cover it.
    technique_rules: dict[str, list[str]] = field(default_factory=dict)

    @property
    def covered_technique_count(self) -> int:
        return len(self.technique_rules)

    @property
    def overall_percentage(self) -> float:
        total = sum(ATTACK_TECHNIQUE_TOTALS.values())
        covered = sum(tc.covered for tc in self.tactics.values())
        return round(100.0 * covered / total, 1) if total else 0.0


def _base_technique(technique: str) -> str:
    """Normalise a (sub-)technique id to its base, e.g. ``T1059.004`` -> ``T1059``."""
    return technique.split(".", 1)[0].upper()


def build_report(rules: list[LoadedRule]) -> CoverageReport:
    """Aggregate ATT&CK coverage from the rules' tactic/technique tags."""
    report = CoverageReport()
    technique_rules: dict[str, set[str]] = defaultdict(set)

    for rule in rules:
        for tactic in rule.tactics:
            tc = report.tactics.setdefault(tactic, TacticCoverage(tactic=tactic))
            for technique in rule.techniques:
                tc.covered_base_techniques.add(_base_technique(technique))
        for technique in rule.techniques:
            technique_rules[technique].add(rule.title)

    report.technique_rules = {
        tech: sorted(titles) for tech, titles in sorted(technique_rules.items())
    }
    return report


def build_navigator_layer(report: CoverageReport, rules: list[LoadedRule]) -> dict:
    """Build an ATT&CK Navigator layer dict highlighting covered techniques."""
    techniques = [
        {
            "techniqueID": technique,
            "score": 1,
            "color": _COVERED_COLOR,
            "comment": "; ".join(titles),
            "enabled": True,
            "metadata": [{"name": "rules", "value": str(len(titles))}],
        }
        for technique, titles in report.technique_rules.items()
    ]

    return {
        "name": "sentinel-as-code coverage",
        "versions": {
            "attack": ATTACK_VERSION,
            "navigator": NAVIGATOR_APP_VERSION,
            "layer": NAVIGATOR_LAYER_VERSION,
        },
        "domain": "enterprise-attack",
        "description": (
            "Techniques covered by tested detection rules in the sentinel-as-code "
            "repository. Generated by `sentinel coverage`."
        ),
        "filters": {"platforms": ["Linux"]},
        "sorting": 0,
        "layout": {"layout": "side", "showID": True, "showName": True},
        "hideDisabled": False,
        "techniques": techniques,
        "gradient": {
            "colors": ["#ffffff", _COVERED_COLOR],
            "minValue": 0,
            "maxValue": 1,
        },
        "legendItems": [{"label": "Covered by a tested rule", "color": _COVERED_COLOR}],
        "metadata": [
            {"name": "rule_count", "value": str(len(rules))},
            {"name": "technique_count", "value": str(report.covered_technique_count)},
        ],
        "showTacticRowBackground": False,
        "tacticRowBackground": "#dddddd",
        "selectTechniquesAcrossTactics": True,
        "selectSubtechniquesWithParent": False,
    }


def render_markdown(report: CoverageReport, rule_count: int) -> str:
    """Render the Markdown coverage summary."""
    lines: list[str] = []
    lines.append("# ATT&CK Coverage Summary")
    lines.append("")
    lines.append(
        f"_Generated by `sentinel coverage` against MITRE ATT&CK Enterprise v{ATTACK_VERSION}._"
    )
    lines.append("")
    lines.append(
        f"- **Rules:** {rule_count}\n"
        f"- **Distinct techniques covered:** {report.covered_technique_count}\n"
        f"- **Tactics with coverage:** {len(report.tactics)} / "
        f"{len(ATTACK_TECHNIQUE_TOTALS)}\n"
        f"- **Overall technique coverage:** {report.overall_percentage}%"
    )
    lines.append("")
    lines.append("## Coverage by tactic")
    lines.append("")
    lines.append("| Tactic | Techniques covered | Tactic total | Coverage |")
    lines.append("| --- | ---: | ---: | ---: |")
    for tactic in sorted(report.tactics):
        tc = report.tactics[tactic]
        lines.append(
            f"| {tactic.replace('_', ' ').title()} | {tc.covered} | {tc.total} | {tc.percentage}% |"
        )
    lines.append("")
    lines.append("## Techniques covered")
    lines.append("")
    lines.append("| Technique | Rules |")
    lines.append("| --- | --- |")
    for technique, titles in report.technique_rules.items():
        lines.append(f"| {technique} | {', '.join(titles)} |")
    lines.append("")
    return "\n".join(lines)


def generate_coverage(detections_dir: Path, out_dir: Path) -> tuple[Path, Path, CoverageReport]:
    """Generate the Navigator layer and Markdown summary, returning their paths."""
    rules = load_rules(detections_dir)
    report = build_report(rules)

    out_dir.mkdir(parents=True, exist_ok=True)
    layer_path = out_dir / "navigator_layer.json"
    summary_path = out_dir / "coverage_summary.md"

    layer = build_navigator_layer(report, rules)
    layer_path.write_text(json.dumps(layer, indent=2) + "\n", encoding="utf-8")
    summary_path.write_text(render_markdown(report, len(rules)), encoding="utf-8")

    logger.info(
        "Coverage: %d techniques across %d tactics (%.1f%% overall)",
        report.covered_technique_count,
        len(report.tactics),
        report.overall_percentage,
    )
    return layer_path, summary_path, report
